### ISSUE TITLE
Plot panel not working on demo

### ISSUE THREAD

**Issue by lhcubillos** [cruise-automation/webviz#402]
Hi! I'm trying to use Webviz to visualize information from an underwater ROV, but I'm having problems with the Plot panel: it is not actually plotting the data. I tried the demo, at https://webviz.io/app/?demo, and it doesn't work as well. I'm in macOS 10.15.3, and the Chrome version I'm using is `Version 80.0.3987.163 (Official Build) (64-bit)`. I attach a screenshot of the problem, using Incognito Mode to try to isolate it. 
![image](https://user-images.githubusercontent.com/12566390/79580050-72576000-8096-11ea-9fd0-a9228e30a412.png)

**Comment by lhcubillos** [comment]
I updated Chrome to `Version 81.0.4044.113` but the problem remains.

**Comment by janpaul123** [comment]
Thanks for letting us know, we totally missed this! https://github.com/cruise-automation/webviz/pull/399 should fix this, but is currently failing CI — @hassoncs is going to look into this today.

**Comment by hassoncs** [comment]
@lhcubillos, this should be fixed now. Sorry that happen and thank you for reporting it!

**Comment by lhcubillos** [comment]
I don't know if I am the problem now, but I still can't see the plotting happening in the demo. 
<img width="1440" alt="Screen Shot 2020-04-20 at 15 16 24" src="https://user-images.githubusercontent.com/12566390/79790629-09801a00-831a-11ea-9c96-dc8f943026fd.png">

I tried erasing the cache and cookies, and working in Incognito, but to no success.

**Comment by janpaul123** [comment]
It took some time to build, but it looks good for me now, can you check again?

**Comment by lhcubillos** [comment]
Now it's working! Thank you very much!

**Comment by janpaul123** [comment]
@lhcubillos I've been reaching out to Webviz users to get to know the community better, and I'd love to learn more about the underwater robots that you use Webviz for. Would you be open to do a quick video call with me some time? If so, can you email me at jp.posma@getcruise.com? 😃
